spring.application.name=Backend

# ====================================================
# CONEXI�N A ORACLE AUTONOMOUS DATABASE (TLS DIRECTO)
# ====================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.port=${SERVER_PORT:8081}

# ====================================================
# CONFIGURACI�N JPA / HIBERNATE (CREACI�N DE TABLAS)
# ====================================================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ====================================================
# CONFIGURACI�N DE TU ENDPOINT DE FASTAPI (PYTHON)
# ====================================================
fastapi.url=${MODEL_API_URL:https://techmind-hackathon.duckdns.org/api/contenido}
